### ISSUE TITLE
Can't convert 'bytes' object to str implicitly

### ISSUE THREAD

**Issue by leonirlopes** [ikreymer/pywb-proxy-demo#1]
```Pywb Error
Can't convert 'bytes' object to str implicitly

Error Details:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pywb/framework/wsgi_wrappers.py", line 65, in handle_methods
    response = wb_router(env)
  File "/usr/local/lib/python3.5/dist-packages/pywb/framework/proxy.py", line 39, in __call__
    response = self.proxy(env)
  File "/usr/local/lib/python3.5/dist-packages/pywb/framework/proxy.py", line 195, in __call__
    route, coll, matcher, ts, response = self.resolver.resolve(env)
  File "/usr/local/lib/python3.5/dist-packages/pywb/framework/proxy_resolvers.py", line 227, in resolve
    return super(CookieResolver, self).resolve(env)
  File "/usr/local/lib/python3.5/dist-packages/pywb/framework/proxy_resolvers.py", line 46, in resolve
    path = '/' + proxy_coll + '/'
TypeError: Can't convert 'bytes' object to str implicitly

```

**Comment by Patiharifinthea** [comment]
??
